### PR TITLE
Bugfix/file handling

### LINKED ISSUE #250: File Upload not working anymore
Hello,

I am using contao 4.9.23 and I have problems with the latest version (1.6.4) of the Notification Center.
I guess due to the changes to the temp directory, the files can't be moved.
Probably because the file is not saved by contao 'uploaded' is not set.

In getFileUploadPathForToken , therefore 
[$filePath = sys_get_temp_dir() . '/' . $file['name'];](https://github.com/terminal42/contao-notification_center/blob/d2070fc8b37f956557755077292e0b04b0d00721/library/NotificationCenter/Util/Form.php#L40)
is set.
In my case this is /var/folders/9m/m_sgcx916xjbd5pbscthgphc0000gq/T/file.ext
In \Files::getInstance()->move_uploaded_file, however, $this->strRootDir is prepended to the target, making it /Users/username/Sites/contao//var/folders/9m/m_sgcx916xjbd5pbscthgphc0000gq/T/file.ext, which is probably not a valid path.

### PR DESCRIPTION
**Pull request by qzminski**
Fixes #250.

### CODE REVIEW

File: library/NotificationCenter/Queue/QueueManager.php [hunk 1]
```diff
@@ -162,12 +161,15 @@ protected function storeFiles(GatewayInterface $gateway, QueuedMessage $queuedMe
 
         // Copy the attachments to the temporary folder
         foreach ($attachments as $index => $originalPath) {
-            $originalPath = str_replace(TL_ROOT . '/', '', $originalPath);
-            $clonePath = $folder->path . '/' . basename($originalPath);
+            $originalPath = '/' === $originalPath[0] ? $originalPath : str_replace(TL_ROOT . '/', '', $originalPath);
```
Comment (fritzmg) [inline library/NotificationCenter/Queue/QueueManager.php:164]: That won't work on Windows. You should use https://packagist.org/packages/webmozart/path-util for that.

File: library/NotificationCenter/Queue/QueueManager.php [hunk 2]
```diff
@@ -162,12 +161,15 @@ protected function storeFiles(GatewayInterface $gateway, QueuedMessage $queuedMe
...
+            $clonePath = TL_ROOT . '/' . $folder->path . '/' . basename($originalPath);
 
             // Update the tokens if copy was successful
-            if (Files::getInstance()->copy($originalPath, $clonePath)) {
-                $attachments[$index] = TL_ROOT . '/' . $clonePath;
+            try {
+                (new Filesystem())->copy($originalPath, $clonePath);
+                $attachments[$index] = $clonePath;
+            } catch (\Exception $exception) {
+                // noop
```
Comment (fritzmg) [inline library/NotificationCenter/Queue/QueueManager.php:172]: I don't think it should silently fail?
